### ISSUE TITLE
v1.0.0 TODO

### ISSUE THREAD

**Issue by meetqy** [meetqy/rao-pics#416]
- [x] <del>#421<del>
- [ ] #422
- [ ] docs
- [x] electron-builder mac x64
- [x] electron-builder win
- [ ] <del>导入主题<del>
- [x] 脚本生成 icons, apps/electron, apps/nextra-docs 软连接到 icons
- [ ] README.md
- [x] #419
